/*
# Seed Kelasi Database with Initial Data

## Overview
Populates the database with the initial school data from the mock-data.ts file.
This includes: 1 school, academic years, terms, subjects, teachers, classrooms,
50 students, 15 parents, student-parent links, attendance, assessments, grades,
invoices, payments, notifications, and announcements.

## Important Notes
1. The `users` table is NOT seeded here — it requires entries in auth.users first.
   User profiles will be created via the signup flow (auth.signUp + profile insert).
2. Teachers reference user_id as NULL for now.
3. All UUIDs are generated by gen_random_uuid().
*/

DO $$
DECLARE
  v_school_id uuid;
  v_ay1_id uuid;
  v_ay2_id uuid;
  v_t1_id uuid;
  v_t2_id uuid;
  v_t3_id uuid;
  v_sub_ids uuid[] := ARRAY[]::uuid[];
  v_teacher_ids uuid[] := ARRAY[]::uuid[];
  v_classroom_ids uuid[] := ARRAY[]::uuid[];
  v_student_ids uuid[] := ARRAY[]::uuid[];
  v_parent_ids uuid[] := ARRAY[]::uuid[];
  v_i integer;
  v_sub_id uuid;
  v_teacher_id uuid;
  v_classroom_id uuid;
  v_student_id uuid;
  v_parent_id uuid;
  v_assessment_ids uuid[] := ARRAY[]::uuid[];
  v_invoice_ids uuid[] := ARRAY[]::uuid[];
  v_first_names text[] := ARRAY['Aimé','Béatrice','Christian','Divine','Emmanuel','Fanny','Gloire','Hélène','Iris','Joël','Kévin','Larissa','Marc','Nadège','Olivier','Prisca','Quentin','Rachel','Steve','Thérèse','Ulrich','Viviane','Wilson','Yannick','Zoé','Ange','Bénédicte','Cédric','Diane','Espérance','Fabrice','Grâce','Hervé','Inès','Josué','Karine','Léon','Mireille','Norbert','Olive','Pascal','Queen','Rudy','Sylvie','Thierry','Ursule','Venance','William','Yolande','Zaire'];
  v_last_names text[] := ARRAY['Mukendi','Kabongo','Mwamba','Ntumba','Ilunga','Kasongo','Mwenze','Tshibangu','Lukusa','Mbiya','Bofando','Mukeba','Kasawu','Bakwa','Nkulu','Mpeza','Tshala','Mbuyi','Kalala','Kabasele','Mwamba','Kibonge','Tshisekedi','Kabila','Lumumba','Mobutu','Kasa-Vubu','Bemba','Katumbi','Madiba','Ngalula','Bashila','Kabange','Mukwege','Tshombe','Sendwe','Mulele','Kengo','Nzuzi','Bola','Delva','Mafuta','Kabongo','Lukusa','Mabiala','Tumba','Kabasele','Mwila','Kasongo','Nkashama'];
  v_professions text[] := ARRAY['Commerçant','Infirmière','Chauffeur','Enseignante','Mécanicien','Secrétaire','Avocat','Coiffeuse','Comptable','Vendeuse','Électricien','Médecin','Architecte','Commerçante','Fonctionnaire'];
  v_quartiers text[] := ARRAY['Matonge','Lemba','Bandalungwa','Ngaliema','Kintambo','Gombe','Ngaba','Selembao','Bandal','Lemba','Matonge','Ngaliema','Bandalungwa','Kintambo','Gombe'];
  v_parent_noms text[] := ARRAY['Jean Mukendi','Adèle Kabongo','Félix Mwamba','Claire Ntumba','Patrick Ilunga','Brigitte Kasongo','Augustin Mwenze','Solange Tshibangu','Robert Lukusa','Nadine Mbiya','Éric Bofando','Grace Mukeba','Daniel Kasawu','Marie Bakwa','Paul Nkulu'];
  v_today date := CURRENT_DATE;
  v_att_statuses text[] := ARRAY['present','present','present','present','present','present','absent','retard','present','justifie'];
  v_montant_total integer;
  v_montant_paye integer;
  v_reste integer;
  v_types text[] := ARRAY['scolarite','inscription','cantine','transport','autre'];
  v_invoice_id uuid;
  v_assessment_id uuid;
  v_note numeric;
  v_status_val text;
  v_payment_id uuid;
BEGIN
  -- 1. SCHOOL
  INSERT INTO schools (id, nom, logo, adresse, telephone, statut_abonnement, date_creation)
  VALUES (gen_random_uuid(), 'École Mixte Lumumba', '', 'Av. de la Victoire, Brazzaville', '+243 81 234 5678', 'actif', '2021-09-01')
  RETURNING id INTO v_school_id;

  -- 2. ACADEMIC YEARS
  INSERT INTO academic_years (id, school_id, libelle, date_debut, date_fin, statut)
  VALUES (gen_random_uuid(), v_school_id, '2026-2027', '2026-09-01', '2027-07-15', 'active')
  RETURNING id INTO v_ay1_id;
  INSERT INTO academic_years (id, school_id, libelle, date_debut, date_fin, statut)
  VALUES (gen_random_uuid(), v_school_id, '2025-2026', '2025-09-01', '2026-07-15', 'archivee')
  RETURNING id INTO v_ay2_id;

  -- 3. TERMS
  INSERT INTO terms (id, school_id, academic_year_id, libelle, date_debut, date_fin)
  VALUES (gen_random_uuid(), v_school_id, v_ay1_id, 'Trimestre 1', '2026-09-01', '2026-12-15')
  RETURNING id INTO v_t1_id;
  INSERT INTO terms (id, school_id, academic_year_id, libelle, date_debut, date_fin)
  VALUES (gen_random_uuid(), v_school_id, v_ay1_id, 'Trimestre 2', '2027-01-05', '2027-04-05')
  RETURNING id INTO v_t2_id;
  INSERT INTO terms (id, school_id, academic_year_id, libelle, date_debut, date_fin)
  VALUES (gen_random_uuid(), v_school_id, v_ay1_id, 'Trimestre 3', '2027-04-20', '2027-07-15')
  RETURNING id INTO v_t3_id;

  -- 4. SUBJECTS (9)
  FOR v_i IN 1..9 LOOP
    INSERT INTO subjects (id, school_id, nom, coefficient)
    VALUES (gen_random_uuid(), v_school_id,
      CASE v_i WHEN 1 THEN 'Mathématiques' WHEN 2 THEN 'Français' WHEN 3 THEN 'Histoire-Géographie' WHEN 4 THEN 'Sciences' WHEN 5 THEN 'Anglais' WHEN 6 THEN 'EPS' WHEN 7 THEN 'Informatique' WHEN 8 THEN 'Religion' WHEN 9 THEN 'Éducation artistique' END,
      CASE v_i WHEN 1 THEN 4 WHEN 2 THEN 4 WHEN 3 THEN 2 WHEN 4 THEN 3 WHEN 5 THEN 2 WHEN 6 THEN 1 WHEN 7 THEN 2 WHEN 8 THEN 1 WHEN 9 THEN 1 END
    )
    RETURNING id INTO v_sub_id;
    v_sub_ids := array_append(v_sub_ids, v_sub_id);
  END LOOP;

  -- 5. TEACHERS (5)
  FOR v_i IN 1..5 LOOP
    INSERT INTO teachers (id, school_id, user_id, nom, prenom, email, telephone, matiere_ids, classroom_ids, statut)
    VALUES (gen_random_uuid(), v_school_id, NULL,
      CASE v_i WHEN 1 THEN 'Tshala' WHEN 2 THEN 'Mpeza' WHEN 3 THEN 'Nkulu' WHEN 4 THEN 'Bakwa' WHEN 5 THEN 'Mbuyi' END,
      CASE v_i WHEN 1 THEN 'Esther' WHEN 2 THEN 'David' WHEN 3 THEN 'Sarah' WHEN 4 THEN 'Michel' WHEN 5 THEN 'Jeanne' END,
      CASE v_i WHEN 1 THEN 'esther.tshala@kelasi.com' WHEN 2 THEN 'david.mpeza@kelasi.com' WHEN 3 THEN 'sarah.nkulu@kelasi.com' WHEN 4 THEN 'michel.bakwa@kelasi.com' WHEN 5 THEN 'jeanne.mbuyi@kelasi.com' END,
      CASE v_i WHEN 1 THEN '+243 81 555 6666' WHEN 2 THEN '+243 81 999 1010' WHEN 3 THEN '+243 82 121 3141' WHEN 4 THEN '+243 82 343 5454' WHEN 5 THEN '+243 81 565 6767' END,
      ARRAY[]::text[], ARRAY[]::text[], 'actif'
    )
    RETURNING id INTO v_teacher_id;
    v_teacher_ids := array_append(v_teacher_ids, v_teacher_id);
  END LOOP;

  -- 6. CLASSROOMS (5)
  INSERT INTO classrooms (id, school_id, niveau, nom, salle, enseignant_principal_id)
  VALUES (gen_random_uuid(), v_school_id, '6ème', '6ème A', 'Salle 101', v_teacher_ids[1])
  RETURNING id INTO v_classroom_id;
  v_classroom_ids := array_append(v_classroom_ids, v_classroom_id);

  INSERT INTO classrooms (id, school_id, niveau, nom, salle, enseignant_principal_id)
  VALUES (gen_random_uuid(), v_school_id, '5ème', '5ème A', 'Salle 102', v_teacher_ids[2])
  RETURNING id INTO v_classroom_id;
  v_classroom_ids := array_append(v_classroom_ids, v_classroom_id);

  INSERT INTO classrooms (id, school_id, niveau, nom, salle, enseignant_principal_id)
  VALUES (gen_random_uuid(), v_school_id, '4ème', '4ème A', 'Salle 201', v_teacher_ids[1])
  RETURNING id INTO v_classroom_id;
  v_classroom_ids := array_append(v_classroom_ids, v_classroom_id);

  INSERT INTO classrooms (id, school_id, niveau, nom, salle, enseignant_principal_id)
  VALUES (gen_random_uuid(), v_school_id, '3ème', '3ème A', 'Salle 202', v_teacher_ids[3])
  RETURNING id INTO v_classroom_id;
  v_classroom_ids := array_append(v_classroom_ids, v_classroom_id);

  INSERT INTO classrooms (id, school_id, niveau, nom, salle, enseignant_principal_id)
  VALUES (gen_random_uuid(), v_school_id, '6ème', '6ème B', 'Salle 103', v_teacher_ids[2])
  RETURNING id INTO v_classroom_id;
  v_classroom_ids := array_append(v_classroom_ids, v_classroom_id);

  -- Update teacher classroom_ids
  UPDATE teachers SET classroom_ids = ARRAY[v_classroom_ids[1]::text, v_classroom_ids[3]::text] WHERE id = v_teacher_ids[1];
  UPDATE teachers SET classroom_ids = ARRAY[v_classroom_ids[2]::text, v_classroom_ids[5]::text] WHERE id = v_teacher_ids[2];
  UPDATE teachers SET classroom_ids = ARRAY[v_classroom_ids[4]::text] WHERE id = v_teacher_ids[3];
  UPDATE teachers SET classroom_ids = ARRAY[v_classroom_ids[1]::text, v_classroom_ids[2]::text, v_classroom_ids[3]::text] WHERE id = v_teacher_ids[4];
  UPDATE teachers SET classroom_ids = ARRAY[v_classroom_ids[4]::text, v_classroom_ids[5]::text] WHERE id = v_teacher_ids[5];

  -- 7. STUDENTS (50)
  FOR v_i IN 1..50 LOOP
    v_classroom_id := CASE WHEN v_i <= 12 THEN v_classroom_ids[1] WHEN v_i <= 22 THEN v_classroom_ids[2] WHEN v_i <= 32 THEN v_classroom_ids[3] WHEN v_i <= 40 THEN v_classroom_ids[4] ELSE v_classroom_ids[5] END;

    INSERT INTO students (id, school_id, matricule, nom, prenom, date_naissance, classroom_id, statut)
    VALUES (gen_random_uuid(), v_school_id,
      'EL' || lpad(v_i::text, 4, '0'),
      v_last_names[((v_i - 1) % array_length(v_last_names, 1)) + 1],
      v_first_names[((v_i - 1) % array_length(v_first_names, 1)) + 1],
      make_date(2010 + floor((v_i - 1) / 12)::int, ((v_i - 1) % 9) + 1, 10 + ((v_i - 1) % 9)),
      v_classroom_id,
      CASE WHEN (v_i - 1) % 30 = 29 THEN 'inactif' ELSE 'actif' END
    )
    RETURNING id INTO v_student_id;
    v_student_ids := array_append(v_student_ids, v_student_id);

    INSERT INTO student_documents (id, school_id, student_id, nom, type, date_ajout)
    VALUES (gen_random_uuid(), v_school_id, v_student_id, 'Acte de naissance', 'PDF', '2026-09-01');
    INSERT INTO student_documents (id, school_id, student_id, nom, type, date_ajout)
    VALUES (gen_random_uuid(), v_school_id, v_student_id, 'Bulletin précédent', 'PDF', '2026-09-01');
    INSERT INTO student_documents (id, school_id, student_id, nom, type, date_ajout)
    VALUES (gen_random_uuid(), v_school_id, v_student_id, 'Photo d''identité', 'JPG', '2026-09-01');

    INSERT INTO enrollments (id, school_id, student_id, classroom_id, academic_year_id, date_inscription, statut)
    VALUES (gen_random_uuid(), v_school_id, v_student_id, v_classroom_id, v_ay1_id, '2026-09-01', 'active');
  END LOOP;

  -- 8. PARENTS (15)
  FOR v_i IN 1..15 LOOP
    INSERT INTO parents (id, school_id, nom, telephone, email, adresse, profession)
    VALUES (gen_random_uuid(), v_school_id,
      v_parent_noms[v_i],
      '+243 8' || (v_i % 2)::text || ' ' || substr(lpad((100 + v_i * 11)::text, 3, '0'), 1, 3) || ' ' || substr(lpad((200 + v_i * 22)::text, 4, '0'), 1, 4),
      lower(replace(v_parent_noms[v_i], ' ', '.')) || '@gmail.com',
      'Quartier ' || v_quartiers[v_i] || ', Kinshasa',
      v_professions[v_i]
    )
    RETURNING id INTO v_parent_id;
    v_parent_ids := array_append(v_parent_ids, v_parent_id);
  END LOOP;

  -- Student-parent links
  FOR v_i IN 1..50 LOOP
    v_parent_id := v_parent_ids[((v_i - 1) % 15) + 1];
    INSERT INTO student_parents (id, school_id, student_id, parent_id)
    VALUES (gen_random_uuid(), v_school_id, v_student_ids[v_i], v_parent_id)
    ON CONFLICT (student_id, parent_id) DO NOTHING;

    IF (v_i - 1) % 5 = 0 THEN
      v_parent_id := v_parent_ids[(((v_i + 3) - 1) % 15) + 1];
      INSERT INTO student_parents (id, school_id, student_id, parent_id)
      VALUES (gen_random_uuid(), v_school_id, v_student_ids[v_i], v_parent_id)
      ON CONFLICT (student_id, parent_id) DO NOTHING;
    END IF;
  END LOOP;

  -- 9. ATTENDANCE (50)
  FOR v_i IN 1..50 LOOP
    v_classroom_id := CASE WHEN v_i <= 12 THEN v_classroom_ids[1] WHEN v_i <= 22 THEN v_classroom_ids[2] WHEN v_i <= 32 THEN v_classroom_ids[3] WHEN v_i <= 40 THEN v_classroom_ids[4] ELSE v_classroom_ids[5] END;

    INSERT INTO attendance (id, school_id, student_id, classroom_id, date, statut)
    VALUES (gen_random_uuid(), v_school_id, v_student_ids[v_i], v_classroom_id, v_today,
      v_att_statuses[((v_i - 1) % array_length(v_att_statuses, 1)) + 1]);
  END LOOP;

  -- 10. ASSESSMENTS (12)
  FOR v_i IN 1..12 LOOP
    v_classroom_id := CASE v_i WHEN 1 THEN v_classroom_ids[1] WHEN 2 THEN v_classroom_ids[1] WHEN 3 THEN v_classroom_ids[1] WHEN 4 THEN v_classroom_ids[1] WHEN 5 THEN v_classroom_ids[2] WHEN 6 THEN v_classroom_ids[2] WHEN 7 THEN v_classroom_ids[3] WHEN 8 THEN v_classroom_ids[3] WHEN 9 THEN v_classroom_ids[4] WHEN 10 THEN v_classroom_ids[4] WHEN 11 THEN v_classroom_ids[5] WHEN 12 THEN v_classroom_ids[5] END;

    INSERT INTO assessments (id, school_id, subject_id, classroom_id, term_id, libelle, date, coefficient)
    VALUES (gen_random_uuid(), v_school_id,
      v_sub_ids[CASE v_i WHEN 1 THEN 1 WHEN 2 THEN 2 WHEN 3 THEN 1 WHEN 4 THEN 4 WHEN 5 THEN 2 WHEN 6 THEN 5 WHEN 7 THEN 3 WHEN 8 THEN 1 WHEN 9 THEN 4 WHEN 10 THEN 2 WHEN 11 THEN 7 WHEN 12 THEN 1 END],
      v_classroom_id, v_t1_id,
      CASE v_i WHEN 1 THEN 'Devoir 1 - Fractions' WHEN 2 THEN 'Dictée - Semaine 3' WHEN 3 THEN 'Interrogation - Géométrie' WHEN 4 THEN 'TP - Écosystèmes' WHEN 5 THEN 'Rédaction - Mon village' WHEN 6 THEN 'Vocabulary Test 1' WHEN 7 THEN 'Contrôle - Colonisation' WHEN 8 THEN 'Devoir 1 - Algèbre' WHEN 9 THEN 'Examen - Chimie' WHEN 10 THEN 'Dissertation - Démocratie' WHEN 11 THEN 'TP - Word Processing' WHEN 12 THEN 'Devoir 1 - Nombres décimaux' END,
      ('2026-10-' || lpad((v_i + 4)::text, 2, '0'))::date,
      CASE v_i WHEN 1 THEN 2 WHEN 2 THEN 1 WHEN 3 THEN 2 WHEN 4 THEN 1 WHEN 5 THEN 2 WHEN 6 THEN 1 WHEN 7 THEN 2 WHEN 8 THEN 2 WHEN 9 THEN 3 WHEN 10 THEN 2 WHEN 11 THEN 1 WHEN 12 THEN 2 END
    )
    RETURNING id INTO v_assessment_id;
    v_assessment_ids := array_append(v_assessment_ids, v_assessment_id);
  END LOOP;

  -- 11. GRADES
  FOR v_i IN 1..12 LOOP
    v_classroom_id := CASE v_i WHEN 1 THEN v_classroom_ids[1] WHEN 2 THEN v_classroom_ids[1] WHEN 3 THEN v_classroom_ids[1] WHEN 4 THEN v_classroom_ids[1] WHEN 5 THEN v_classroom_ids[2] WHEN 6 THEN v_classroom_ids[2] WHEN 7 THEN v_classroom_ids[3] WHEN 8 THEN v_classroom_ids[3] WHEN 9 THEN v_classroom_ids[4] WHEN 10 THEN v_classroom_ids[4] WHEN 11 THEN v_classroom_ids[5] WHEN 12 THEN v_classroom_ids[5] END;

    FOR v_j IN 1..50 LOOP
      v_student_id := v_student_ids[v_j];
      PERFORM 1 FROM students WHERE id = v_student_id AND classroom_id = v_classroom_id;
      IF FOUND THEN
        v_note := round((8 + (mod(v_j * 3 + v_i * 2, 12)) * 2) / 2, 1);
        v_status_val := CASE WHEN v_i <= 4 THEN 'publie' WHEN v_i <= 8 THEN 'valide' ELSE 'brouillon' END;

        INSERT INTO grades (id, school_id, assessment_id, student_id, note, statut_validation)
        VALUES (gen_random_uuid(), v_school_id, v_assessment_ids[v_i], v_student_id, v_note, v_status_val);
      END IF;
    END LOOP;
  END LOOP;

  -- 12. INVOICES (50)
  FOR v_i IN 1..50 LOOP
    v_montant_total := 250000 + (mod(v_i - 1, 4)) * 50000;
    v_montant_paye := CASE WHEN mod(v_i - 1, 5) = 0 THEN v_montant_total WHEN mod(v_i - 1, 3) = 0 THEN floor(v_montant_total * 0.5)::int WHEN mod(v_i - 1, 4) = 0 THEN 100000 ELSE 0 END;
    v_reste := v_montant_total - v_montant_paye;

    INSERT INTO invoices (id, school_id, student_id, type_frais, montant_total, montant_paye, reste_a_payer, date_emission, statut)
    VALUES (gen_random_uuid(), v_school_id, v_student_ids[v_i],
      v_types[mod(v_i - 1, 5) + 1],
      v_montant_total, v_montant_paye, v_reste,
      ('2026-09-0' || (mod(v_i - 1, 9) + 1)::text)::date,
      CASE WHEN v_reste = 0 THEN 'paye' WHEN v_montant_paye > 0 THEN 'partiel' ELSE 'impaye' END
    )
    RETURNING id INTO v_invoice_id;
    v_invoice_ids := array_append(v_invoice_ids, v_invoice_id);
  END LOOP;

  -- 13. PAYMENTS + receipts
  FOR v_i IN 1..50 LOOP
    v_montant_total := 250000 + (mod(v_i - 1, 4)) * 50000;
    v_montant_paye := CASE WHEN mod(v_i - 1, 5) = 0 THEN v_montant_total WHEN mod(v_i - 1, 3) = 0 THEN floor(v_montant_total * 0.5)::int WHEN mod(v_i - 1, 4) = 0 THEN 100000 ELSE 0 END;

    IF v_montant_paye > 0 THEN
      INSERT INTO payments (id, school_id, invoice_id, montant, date_paiement, mode_paiement, partiel)
      VALUES (gen_random_uuid(), v_school_id, v_invoice_ids[v_i], v_montant_paye,
        ('2026-09-0' || (mod(v_i - 1, 9) + 1)::text)::date,
        CASE mod(v_i - 1, 4) WHEN 0 THEN 'especes' WHEN 1 THEN 'mobile_money' WHEN 2 THEN 'virement' WHEN 3 THEN 'cheque' END,
        CASE WHEN v_montant_total - v_montant_paye > 0 THEN true ELSE false END
      )
      RETURNING id INTO v_payment_id;

      INSERT INTO receipts (id, school_id, payment_id, reference, date_generation)
      VALUES (gen_random_uuid(), v_school_id, v_payment_id, 'REC-' || lpad(v_i::text, 6, '0'), now());
    END IF;
  END LOOP;

  -- 14. NOTIFICATIONS (10)
  INSERT INTO notifications (id, school_id, type, destinataire_id, canal, message, statut, date) VALUES
  (gen_random_uuid(), v_school_id, 'paiement', 'p1', 'sms', 'Paiement de 250.000 FC reçu pour Aimé Mukendi. Merci!', 'envoye', '2026-10-15T08:30:00'),
  (gen_random_uuid(), v_school_id, 'absence', 'p2', 'sms', 'Votre enfant Béatrice Kabongo était absent(e) aujourd''hui. Veuillez justifier.', 'envoye', '2026-10-15T09:00:00'),
  (gen_random_uuid(), v_school_id, 'annonce', 'all', 'in-app', 'Réunion parents-professeurs le 25 octobre à 10h.', 'envoye', '2026-10-14T14:00:00'),
  (gen_random_uuid(), v_school_id, 'bulletin', 'p1', 'email', 'Le bulletin du Trimestre 1 de Aimé Mukendi est disponible.', 'en_attente', '2026-10-15T10:00:00'),
  (gen_random_uuid(), v_school_id, 'nouvel_eleve', 'u1', 'in-app', 'Nouvel élève inscrit: Christian Mwamba (6ème A).', 'envoye', '2026-10-13T11:00:00'),
  (gen_random_uuid(), v_school_id, 'paiement', 'p3', 'sms', 'Rappel: frais de scolarité en attente de paiement.', 'echec', '2026-10-15T07:00:00'),
  (gen_random_uuid(), v_school_id, 'absence', 'p5', 'sms', 'Votre enfant Gloire Mwenze était en retard aujourd''hui.', 'envoye', '2026-10-15T09:15:00'),
  (gen_random_uuid(), v_school_id, 'annonce', 'all', 'in-app', 'Les bulletins du 1er trimestre seront disponibles le 18 décembre.', 'envoye', '2026-10-13T16:00:00'),
  (gen_random_uuid(), v_school_id, 'paiement', 'p7', 'email', 'Reçu de paiement disponible pour téléchargement.', 'envoye', '2026-10-14T11:00:00'),
  (gen_random_uuid(), v_school_id, 'nouvel_eleve', 'u1', 'in-app', 'Nouvel élève inscrit: Divine Ntumba (5ème A).', 'envoye', '2026-10-12T08:00:00');

  -- 15. ANNOUNCEMENTS (6)
  INSERT INTO announcements (id, school_id, auteur_id, auteur_nom, cible, titre, contenu, date_publication) VALUES
  (gen_random_uuid(), v_school_id, NULL, 'Joseph Kabasele', 'tous', 'Réunion parents-professeurs', 'La réunion parents-professeurs se tiendra le 25 octobre 2026 à 10h dans la grande salle. La présence d''au moins un parent par élève est obligatoire.', '2026-10-14T14:00:00'),
  (gen_random_uuid(), v_school_id, NULL, 'Joseph Kabasele', 'parents', 'Paiement des frais du 2ème trimestre', 'Nous rappelons aux parents que les frais du 2ème trimestre doivent être payés avant le 5 janvier 2027. Merci de votre compréhension.', '2026-10-12T09:00:00'),
  (gen_random_uuid(), v_school_id, NULL, 'Esther Tshala', 'classe', 'Sortie pédagogique 6ème A', 'Une sortie pédagogique est prévue pour la classe de 6ème A le 20 octobre au Parc de la Vallée. Contribution: 5.000 FC par élève.', '2026-10-10T16:00:00'),
  (gen_random_uuid(), v_school_id, NULL, 'Joseph Kabasele', 'enseignants', 'Conseil de classe', 'Le conseil de classe du 1er trimestre se tiendra le 18 décembre à 14h. Préparez vos appréciations.', '2026-10-08T10:00:00'),
  (gen_random_uuid(), v_school_id, NULL, 'Marie Kalala', 'tous', 'Vacances de la Toussaint', 'L''école sera fermée du 28 octobre au 3 novembre 2026 pour les vacances de la Toussaint. Les cours reprennent le 4 novembre.', '2026-10-11T15:00:00'),
  (gen_random_uuid(), v_school_id, NULL, 'Esther Tshala', 'classe', 'Devoir de rattrapage', 'Un devoir de rattrapage en mathématiques aura lieu le 22 octobre pour les élèves ayant raté le Devoir 1.', '2026-10-09T12:00:00');

END $$;
